# Generated by Django 4.0.4 on 2022-06-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=51.477928)),
                ('long', models.FloatField(default=-0.001545)),
            ],
        ),
    ]
