# Generated by Django 4.0.4 on 2022-06-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplanner_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='id',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='coordinate_order',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
